### ISSUE TITLE
Error in IssueTokenTrait.php (line 14)

### ISSUE THREAD

**Issue by christophschoeni** [ProgrammationAndroid/Laravel-Passport-Android#2]
Salut Tutto::Code
J'ai trouvé ton vidéo par hasard et je suis très contente à ce sujet. J'ai remarqué que lorsque j'ai essayé de m'inscrire via le link "http://test.dev/api/register", j'ai l'erreur "ErrorException Trying to get property of non-object in IssueTokenTrait.php (line 14)". Mais le neaveau user a été faite dans le DB.

**Comment by ProgrammationAndroid** [comment]
Salut ;). Il faudrait plus d'infos. T'as bien importé tous les namespaces ? Faudrait la stacktrace complète pour voir.
