### ISSUE TITLE
Logout not implemented

### ISSUE THREAD

**Issue by rexdarel** [ProgrammationAndroid/Laravel-Passport-Android#4]
Hey guys, Thanks for the tutorial but it seems that the logout feature is not implemented yet and I need it. Any ideas when can you do this?

**Comment by lmiskovic** [comment]
basicly comes down to implementing logout method in LoginController

```
    public function logout(Request $request){
    	$accessToken = Auth::user()->token();
    	DB::table('oauth_refresh_tokens')
    		->where('access_token_id', $accessToken->id)
    		->update(['revoked' => true]);
    	$accessToken->revoke();
    	return response()->json([], 204);
    }
```
and adding a route in api.php

`    Route::post('logout', 'Api\Auth\LoginController@logout');
`

on android side u would need to add that route to an ApiInterface like this:

```
    @POST("logout")
    @FormUrlEncoded
    Call<AccessToken> logout(@Field("access_token") AccessToken accessToken);
```

and call it like this 

```
tokenManager = TokenManager.getInstance(getSharedPreferences("prefs", MODE_PRIVATE));
                call = service.logout(tokenManager.getToken());
                call.enqueue(new Callback<AccessToken>() {
                    @Override
                    public void onResponse(Call<AccessToken> call, Response<AccessToken> response) {

                        getSharedPreferences("prefs", MODE_PRIVATE).edit().clear().apply();
                        tokenManager.deleteToken();
                        Intent intent = new Intent(mapActivity.this, loginActivity.class);
                        intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                        startActivity(intent);
                        finish();
                    }

                    @Override
                    public void onFailure(Call<AccessToken> call, Throwable t) {

                    }
                });
```

hope this helps you, u might need to adapt the code, this is from the sample i created while ago, feel free to check it

**Comment by rexdarel** [comment]
thanks. correct me if I'm wrong. I was looking the android side on your code but can't see it so I raise this issue. but thank you

**Comment by lmiskovic** [comment]
[this](https://github.com/lmiskovic/Delivery) is the android project i created by following this tutorial. the code is a mess, but hope it can help you

**Comment by rexdarel** [comment]
thank you man. greatly appreciated.

**Comment by rexdarel** [comment]
there are no other tutorials about laravel and android so even if I can't understand the tutorial I stick to it. SO thank you.
